### PR TITLE
Add using of solidAuth.trackSession() for check, if User is SignedIn already

### PR DESCRIPTION
**Pull request by smalinin**
Recreate https://github.com/linkeddata/dokieli/pull/256 for new sources in master branch

### CODE REVIEW

**Comment by csarven** [comment]
Thanks!

* Can you please rebase to have a single commit? https://github.com/linkeddata/dokieli/commit/7cca3b99d8ca066a7c54fb2a483e4b75833e780d does not need to be in the commit history. (Possibly useful: you might want to use https://help.github.com/articles/syncing-a-fork/ and https://help.github.com/articles/configuring-a-remote-for-a-fork/ and to branch off the latest in master for PRs)

* Also, I don't think I understand the issue/improvement. Can you please elaborate? What was not working so well (and how to reproduce) and how this PR resolves that. It is so that I better understand where you are coming from.

**Comment by smalinin** [comment]
The solid-auth-client that method .trackSession(), that could be used for get state of OIDC session, so we could check, if we LoggedIn already via OIDC(may be in another browser tab with same location.origin or etc).

**Comment by csarven** [comment]
It sounds like it might resolve potential issues with token expiry (see https://github.com/linkeddata/dokieli/issues/257#issuecomment-437655149 and https://github.com/linkeddata/dokieli/issues/255#issuecomment-437660303 ) .. What do you think?

**Comment by csarven** [comment]
I got a chance to look into this.. and solid-auth-client's trackSession doesn't appear to work as this PR intends to. It seems to only "invoke the callback with the current session, and notify you of any changes to the login status." ( https://github.com/solid/solid-auth-client#getting-the-current-user )

I've also noticed that the way trackSession is in place conflicts with the toggling of the user signin/out buttons.

We need to refactor a bit if we want to use trackSession, and I prefer to do that from scratch because the branches are already out of sync

**Comment by smalinin** [comment]
@csarven Ok, I will rewrite code with new function solid.auth.currentSession

**Comment by csarven** [comment]
Hang on.. do we actually need it? The toggling works fine. As far as I can see, the session is not shared across tabs/windows.. am I overlooking something?

**Pull request closed without merging**
