### PR TITLE
Added OpenID Connect (OIDC) authentication protocol support via solid-auth-client. Net effect, both WebID-TLS and WebID-OIDC protocols are now supported.  (Fixed)

### PR DESCRIPTION
**Pull request by smalinin**
I created fresh fork and create new PR.
- `tabs` permissions was removed, it work without it also.
- the code
```
"externally_connectable": {
    "matches": ["https://*.solid.openlinksw.com:8444/*", "https://solid.openlinksw.com:8444/*"]
  }
```
was removed from manifest, it was used with some initial tests. It isn't required.

```
Why is that kind of reliance on any third-party service required? If absolutely required, 
would it be better to make that available from dokie.li?
```
You could put `popup.html` file to dokie.li host and use fix location in `config.js`, note it must be hosted on https://

```
-  scripts/solid-auth-client.bundle.js should be perhaps src/solid-auth-client.build.js, and built into
 scripts/do.js (via package.json). Is there any reason why that needs to be included separately 
in HTML? Is solid-auth-client in npm? Aside: we're trying to avoid adding new scripts into HTML. 
Going forward everything (including simplerdf.js, medium-editor.js etc..) will be built into do.js, 
so it'd be great if we can avoid HTML updates.
```
I tried to build it into scripts/do.js,  BUT I could not get the worked version with some warnings and it looks, that some modules weren't added to scripts/do.js
You could try do it, may be you could found the solution for properly packaging. 
It is required need `solid-auth-client@2.2.9` .
```
 Is everything in scripts/solid-auth-client.bundle.js (369388 bytes) required? 
Is scripts/solid-auth-client.bundle.js.map (480385 bytes) required?
```
Yes, everythyng from `scripts/solid-auth-client.bundle.js` is required, it is the standard built from [](https://github.com/solid/solid-auth-client)
The file scripts/solid-auth-client.bundle.js.map was added for enable debug code, you could remove it.

```
    When I click on 'Sign in OIDC', I get the following in console:

ReferenceError: solid is not defined [Learn more] auth.js:229
  submitSignInOIDC auth.js:229
```
May be solid-auth-client.bundle.js wasn't loaded, I don't have such error.

### CODE REVIEW

**Comment by csarven** [comment]
Works now, thanks.

Can popup.html be integrated into do.js as opposed to dynamically fetching that? It will remove sign in from a server dependency, as well as keeping the user's activity more private ie. dokie.li server doesn't have to know anything.

**Comment by csarven** [comment]
Some of the changes to manifest.json , extension-background.js , extension-content-script.js still appear to be incorporating old code with the new addition for OIDC support.

**Comment by smalinin** [comment]
> Works now, thanks.
> 
> Can popup.html be integrated into do.js as opposed to dynamically fetching that? It will remove sign in from a server dependency, as well as keeping the user's activity more private ie. dokie.li server doesn't have to know anything.

The popup.html must be hosted on https://  server, the another variants will not work, I think.  I tried to add it to extension, but Chrome write errors in console, when it try load it.

**Comment by csarven** [comment]
Regarding including solid-auth-client in package.json and adding `const solid = require('solid-auth-client')` in auth.js, are you getting:
```
WARNING in ./node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js
84:22-60 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js
 @ ./node_modules/@trust/webcrypto/src/algorithms/index.js
 @ ./node_modules/@trust/webcrypto/src/SubtleCrypto.js
 @ ./node_modules/@trust/webcrypto/src/Crypto.js
 @ ./node_modules/@trust/webcrypto/src/index.js
 @ ./node_modules/@solid/oidc-rp/src/AuthenticationResponse.js
 @ ./node_modules/@solid/oidc-rp/src/RelyingParty.js
 @ ./node_modules/@solid/oidc-rp/src/index.js
 @ ./node_modules/solid-auth-client/lib/webid-oidc.js
 @ ./node_modules/solid-auth-client/lib/solid-auth-client.js
 @ ./node_modules/solid-auth-client/lib/index.js
 @ ./src/auth.js
 @ ./src/dokieli.js
 @ multi ./src/dokieli.js
```

 as well?

@dmitrizagidulin Do the @trust/webcrypto stuff up there seem something obvious to you? I vaguely recall discussions around that stuff being deprecated?

**Comment by smalinin** [comment]
> > Works now, thanks.
> > Can popup.html be integrated into do.js as opposed to dynamically fetching that? It will remove sign in from a server dependency, as well as keeping the user's activity more private ie. dokie.li server doesn't have to know anything.
> 
> The popup.html must be hosted on https:// server, the another variants will not work, I think. I tried to add it to extension, but Chrome write errors in console, when it try load it.

For manifest.json - the proprly size images were added and injection on new solid-auth-client
For extension-background.js , extension-content-script.js - all updates exclude next in extension-content-script.js
```
        if (!C.Loaded) {
          var bodyAttributes = {
            "about": "",
            "prefix": "rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# rdfs: http://www.w3.org/2000/01/rdf-schema# owl: http://www.w3.org/2002/07/owl# xsd: http://www.w3.org/2001/XMLSchema# dcterms: http://purl.org/dc/terms/ dctypes: http://purl.org/dc/dcmitype/ foaf: http://xmlns.com/foaf/0.1/ pimspace: http://www.w3.org/ns/pim/space# cc: https://creativecommons.org/ns# skos: http://www.w3.org/2004/02/skos/core# prov: http://www.w3.org/ns/prov# mem: http://mementoweb.org/ns# qb: http://purl.org/linked-data/cube# schema: http://schema.org/ void: http://rdfs.org/ns/void# rsa: http://www.w3.org/ns/auth/rsa# cert: http://www.w3.org/ns/auth/cert# wgs: http://www.w3.org/2003/01/geo/wgs84_pos# bibo: http://purl.org/ontology/bibo/ sioc: http://rdfs.org/sioc/ns# doap: http://usefulinc.com/ns/doap# dbr: http://dbpedia.org/resource/ dbp: http://dbpedia.org/property/ sio: http://semanticscience.org/resource/ opmw: http://www.opmw.org/ontology/ deo: http://purl.org/spar/deo/ doco: http://purl.org/spar/doco/ cito: http://purl.org/spar/cito/ fabio: http://purl.org/spar/fabio/ oa: http://www.w3.org/ns/oa# as: https://www.w3.org/ns/activitystreams# ldp: http://www.w3.org/ns/ldp# solid: http://www.w3.org/ns/solid/terms# acl: http://www.w3.org/ns/auth/acl# dio: https://w3id.org/dio# rel: https://www.w3.org/ns/iana/link-relations/relation#",
            "typeof": "schema:CreativeWork sioc:Post prov:Entity schema:Article"
          }

          Object.keys(bodyAttributes).forEach(function(attribute){
            if(!document.body.getAttribute(attribute)){
              document.body.setAttribute(attribute, bodyAttributes[attribute]);
            }
          });

        document.body.innerHTML = '<main class="article" id="content" about="" typeof="schema:Article">' + document.body.innerHTML + '</main>';

```
related with properly communication with new version of YouID extension for get WebID-Delegate.
The above code may be changed to something better, if you need it.

**Comment by smalinin** [comment]
> Are you getting:
> 
> ```
> WARNING in ./node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js
> 84:22-60 Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/@trust/webcrypto/src/algorithms/SupportedAlgorithms.js
>  @ ./node_modules/@trust/webcrypto/src/algorithms/index.js
>  @ ./node_modules/@trust/webcrypto/src/SubtleCrypto.js
>  @ ./node_modules/@trust/webcrypto/src/Crypto.js
>  @ ./node_modules/@trust/webcrypto/src/index.js
>  @ ./node_modules/@solid/oidc-rp/src/AuthenticationResponse.js
>  @ ./node_modules/@solid/oidc-rp/src/RelyingParty.js
>  @ ./node_modules/@solid/oidc-rp/src/index.js
>  @ ./node_modules/solid-auth-client/lib/webid-oidc.js
>  @ ./node_modules/solid-auth-client/lib/solid-auth-client.js
>  @ ./node_modules/solid-auth-client/lib/index.js
>  @ ./src/auth.js
>  @ ./src/dokieli.js
>  @ multi ./src/dokieli.js
> ```
> 
> as well?

Yes

**Comment by csarven** [comment]
> For manifest.json - the proprly size images were added and injection on new solid-auth-client

Not required for the functionality of this PR. Aside: we're using the largest logo and letting downscaling happen wherever used (for now). Minor to this issue in any case.

>related with properly communication with new version of YouID extension for get WebID-Delegate.

Not required for the functionality of this PR.

The current code uses `if (!C.Loaded && !document.querySelector('#document-menu'))` .. the new code uses `if (!C.Loaded) {` .. any particular reason for that change? Is it required for the functionality of this PR.

I'm assuming that the core of what the PR is supposed to do is getting OIDC auth working.

Don't get me wrong. The PR works as advertised. I'm just trying to minimise bugs coming in or having regression issues, and also not retesting things that previously worked. I don't mind making the changes myself as part of a clean-up of this PR but I'd like to make sure they're all accounted for. So, if there are any line changes that's not absolutely required for OIDC auth, I think they should be left out of the commits. Existing code shouldn't just disappear either eg. `auth.submitSignIn(iri)` - It is hard for me to see why just by looking at the new code and without extensive testing. Anything additional - nice to haves - can be their own PRs eg. changes to YouID functionality...

**Comment by smalinin** [comment]
Ok, I have removed all unrelated changes.

**Comment by smalinin** [comment]
Note, the code ` auth.submitSignIn(iri)` was replaced with `DO.C.User.WebIdDelegate = iri;` for avoid AutoLogin

**Comment by csarven** [comment]
Cool! Would you mind git rebase so that we only retain the essential changes in commit history? (or should I if you're not up to it?)

Before merging, I'd like to resolve two things (I'm currently investigating this, if you have ideas on how we can, that'd be great!):
* getting it working with solid-auth-client in package.json (MUST)
* popup.html behaviour being native to dokieli (and not fetched from server) (SHOULD)

**Comment by csarven** [comment]
BTW, is there any difference between npm solid-auth-client and scripts/solid-auth-client.bundle.js?

**Comment by smalinin** [comment]
> BTW, is there any difference between npm solid-auth-client and scripts/solid-auth-client.bundle.js?

No

**Comment by smalinin** [comment]
> Cool! Would you mind git rebase so that we only retain the essential changes in commit history? (or should I if you're not up to it?)
> 
> Before merging, I'd like to resolve two things (I'm currently investigating this, if you have ideas on how we can, that'd be great!):
> 
>     * getting it working with solid-auth-client in package.json (MUST)
> 
>     * popup.html behaviour being native to dokieli (and not fetched from server) (SHOULD)

I could create squash commits only on local git, but I could not push changes to github.

**Comment by csarven** [comment]
Hmm, what was the error/warning from GitHub?

**Comment by smalinin** [comment]
> Hmm, what was the error/warning from GitHub?

Solved, I run push from command line and it worked properly without errors(I used SmartGit, but it looks some options was not set properly)

**Comment by csarven** [comment]
Thank you! This is so much easier to review.

Note: src/dokieli.js `@@ -1869,10 +1869,9 @@` and `@@ -3841,15 +3840,20 @@` appears to revert to earlier commit (and unrelated to this PR)

I don't quite understand (re extension-content-script.js):
> Note, the code auth.submitSignIn(iri) was replaced with DO.C.User.WebIdDelegate = iri; for avoid AutoLogin

Can you elaborate? Why is that functionality being changed?

Is this in src/auth.js necessary:
> if (window.location.protocol === "https:")

Is it to prevent current document on "http" from taking any information from a signed in user (via OIDC)? or related to the popup.html somehow (even though popup.html is expected to be served from "https")? or is there another reason?

---

I think everything else is fine. I would still like to get the following working before merging:
>getting it working with solid-auth-client in package.json (MUST)

Although I have a **strong** dislike for serving popurl.html, I can live with it for the time being. That can be resolved separately.

**Comment by smalinin** [comment]
> Note: src/dokieli.js `@@ -1869,10 +1869,9 @@` and `@@ -3841,15 +3840,20 @@` appears to revert to earlier commit (and unrelated to this PR)

Fixed

**Comment by smalinin** [comment]
> I don't quite understand (re extension-content-script.js):
> 
> > Note, the code auth.submitSignIn(iri) was replaced with DO.C.User.WebIdDelegate = iri; for avoid AutoLogin
> 
> Can you elaborate? Why is that functionality being changed?

Before:
When you click on Extension button, it receive a selected WebID from YouID extension, 
inject Dokieli code and execute AutoLogin with the WebID.
Therefore you was need(without new changes) to click on Logout and Login again via OIDC.

Now:
it receive a selected WebID from YouID extension, 
inject Dokieli code and use the WebID ONLY for fill field `HTTP(S) IRI` in Login dialog.

**Comment by smalinin** [comment]
> > if (window.location.protocol === "https:")
> 
> Is it to prevent current document on "http" from taking any information from a signed in user (via OIDC)? or related to the popup.html somehow (even though popup.html is expected to be served from "https")? or is there another reason?

Yes, it is related with comminucation with popup.html, that served from https://.

**Comment by csarven** [comment]
>Fixed

FYI, that's only in do.js. I think that should happen in src/dokieli.js and build the do.js. Any way, minor.

I'll look into auth.submitSignIn later.. I don't quite get it right now.

I'll look into getting solid-auth-client working via package.json

**Comment by csarven** [comment]
Accepting this PR as is into the dev/oidc branch. Will do the remaining parts there. We're almost there. Thanks for bringing this PR forward! :)

**Pull request merged**
