### PR TITLE
Fixed issue with insert Embeded Data

### PR DESCRIPTION
**Pull request by smalinin**
The current implementation inserts <script> </script> tag twice after the edit existed embeded code and added `#` for some types.

### CODE REVIEW

**Comment by csarven** [comment]
Thank you for the PR.

I can't reproduce the issue as mentioned at https://gitter.im/linkeddata/dokieli?at=59b8ec73177fb9fe7eb5048a .

On which documents can this issue be reproduced?

`#` is required for Turtle CDATA as mentioned at https://gitter.im/linkeddata/dokieli?at=59b8f1351081499f1f26beb2

**Comment by kidehen** [comment]
@csarven,

If there is no conflict why do we have the following diff excerpt? 


```
-            cdataStart: '# ' + DO.C.CDATAStart + '\n',
 -            cdataEnd: '\n# ' + DO.C.CDATAEnd,
 +            cdataStart: DO.C.CDATAStart + '\n',
 +            cdataEnd: '\n' + DO.C.CDATAEnd,
```


This issue is specific to use of the "Embed Data" control re. RDF-Turtle.  You create this problem by opening the document (see derivation source) as per:

I've created 3 documents which hopefully shed light on this issue:
[1] https://id.myopenlink.net/DAV/home/KingsleyUyiIdehen/RWW/f13614fc-8ff2-4557-891a-5aaa96de2824?author=true -- Uses Nanotation (basically RDF-Turtle inside {} that's sniffed by OSDS) inline and results are identical, irrespective of which dokieli variant is used (outcome: success )
[2] https://id.myopenlink.net/DAV/home/KingsleyUyiIdehen/RWW/wired-bmi-post-2 -- uses "Embed Data" control via dokieli extension currently published to Chrome Store (outcome: fail; simply click on OSDS or view HTML source)
[3] https://id.myopenlink.net/DAV/home/KingsleyUyiIdehen/RWW/wired-bmi-post-3 -- uses "Embed Data" control via our dokieli extension fork (outcome: success; simply click on OSDS or view HTML source)

BTW -- are you testing this matter with the same release published to Google Chrome Store? I have our fork and the version you released to Chrome Store installed, and used in this test.

**Comment by smalinin** [comment]
Ok, but the problem isn't only with `#`

**Comment by smalinin** [comment]
Ok, but the problem isn't only with `#` 
Try the next:
1) Insert Turtle EmbedData like  `<a> <b> <c> .` and you will have the next HTML code in dom
```
<script id="meta-turtle" title="Turtle" type="text/turtle"># //<![CDATA[
<a> <b> <c> .
# //]]></script>
```
Looks Ok.
2) Open Embed Data again, edit it `<a> <b> <c1> .` , save and you will have the next HTML code
```
<script id="meta-turtle" title="Turtle" type="text/turtle">  <script id="meta-turtle" title="Turtle" type="text/turtle"># //<![CDATA[
<a> <b> <c1> .
# //]]></script></script>
```
This isn't fine.

**Review by csarven — CHANGES_REQUESTED** [review]
`cdataStart/End` lines do not need to be changed for this issue. Refactoring the `scriptContent` parts alone appears to fix this issue. Would you mind git rebasing to only include the scriptContent bits?

**Comment by csarven** [comment]
Step 2 is clear, thanks @smalinin . I can reproduce the issue. Please note my minor change request https://github.com/linkeddata/dokieli/pull/217#pullrequestreview-62818832 . I can merge after that.

**Review by kidehen — APPROVED** [review]

**Comment by smalinin** [comment]
I have updated my commit.

**Comment by csarven** [comment]
Thanks!

**Pull request merged**
